Repository boostorg/boost-ci, pull requests merged in 2020-03, with the labels that each got.

#39 Sort the Travis builds by importance:
  templates/.travis.yml
Labels: enhancement

#27 Fix Bash syntax for clang globs matching
  ci/azure-pipelines/install.sh
  ci/travis/install.sh
Labels: bug

#28 Replace non-standard `which` with built-i `command -v`
  ci/azure-pipelines/install.sh
  ci/travis/codecov.sh
  ci/travis/install.sh
  templates/azure-pipelines.yml
Labels: annoyance

#35 Boost requires Jamfile in test/
  ci/appveyor/mingw.bat
  ci/azure-pipelines/build.sh
  ci/travis/build.sh
  templates/appveyor.yml
  templates/azure-pipelines.yml
Labels: annoyance

#44 Revert "Remove .codecov.yml"
  .codecov.yml
  templates/.travis.yml
  templates/azure-pipelines.yml
Labels: bug

#51 AzP: Fix matrix configuration names according to required rules
  templates/azure-pipelines.yml
Labels: bug
